name = "cwaax"
main = "worker/index.ts"
compatibility_date = "2026-09-05"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "84cd18cebe8a49f79e170ea4c5c9b6df"

[vars]
API_ALLOWED_ORIGINS = "https://cwaax.vfshj.workers.dev"
