import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { CwaLogo, IconButton } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
export default function ForgotPasswordScreen() { const router = useRouter(); const [email, setEmail] = useState(""); return <ScreenContainer className="px-6" edges={["top", "left", "right"]}><View style={styles.content}><View style={styles.header}><IconButton icon="arrow-forward" label="رجوع" onPress={() => router.back()}/><CwaLogo/></View><View style={styles.icon}><MaterialIcons name="lock-reset" size={30} color={CWAAX.green}/></View><Text style={styles.title}>استعادة كلمة المرور</Text><Text style={styles.subtitle}>أدخل بريدك الإلكتروني وسنرسل لك رابطاً آمناً لإعادة تعيين كلمة المرور.</Text><Text style={styles.label}>البريد الإلكتروني</Text><View style={styles.input}><MaterialIcons name="mail-outline" size={18} color={CWAAX.muted}/><TextInput value={email} onChangeText={setEmail} placeholder="name@email.com" placeholderTextColor="#9CA8A1" style={styles.field} keyboardType="email-address"/></View><Pressable onPress={() => { if (!email) { Alert.alert("أدخل بريدك", "اكتب البريد الإلكتروني المرتبط بحسابك."); return; } Alert.alert("تم إرسال الرابط", "تحقق من صندوق بريدك لإعادة تعيين كلمة المرور.", [{ text: "العودة للدخول", onPress: () => router.replace("/login") }]); }} style={({ pressed }) => [styles.button, pressed && styles.pressed]}><Text style={styles.buttonText}>إرسال رابط الاستعادة</Text></Pressable></View></ScreenContainer> }
const styles = StyleSheet.create({ content: { flex: 1, paddingTop: 26 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, icon: { width: 62, height: 62, borderRadius: 22, backgroundColor: CWAAX.greenSoft, alignItems: "center", justifyContent: "center", marginTop: 74, alignSelf: "flex-end" }, title: { color: CWAAX.ink, fontSize: 28, fontWeight: "900", textAlign: "right", marginTop: 18 }, subtitle: { color: CWAAX.muted, fontSize: 12, lineHeight: 19, textAlign: "right", marginTop: 8, marginBottom: 25 }, label: { color: CWAAX.ink, fontSize: 12, fontWeight: "800", textAlign: "right", marginBottom: 8 }, input: { height: 52, borderWidth: 1, borderColor: CWAAX.line, borderRadius: 14, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 13 }, field: { flex: 1, color: CWAAX.ink, textAlign: "right", fontSize: 12 }, button: { height: 52, borderRadius: 15, backgroundColor: CWAAX.green, justifyContent: "center", alignItems: "center", marginTop: 18 }, buttonText: { color: CWAAX.white, fontSize: 13, fontWeight: "900" }, pressed: { opacity: .62 } });
