import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { CwaLogo } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
import { startOAuthLogin } from "@/constants/oauth";
export default function LoginScreen() { const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [remember, setRemember] = useState(true); const [loading, setLoading] = useState(false); const login = async () => { if (!email || !password) { Alert.alert("بيانات ناقصة", "أدخل البريد الإلكتروني وكلمة المرور."); return; } setLoading(true); await startOAuthLogin(); setTimeout(() => setLoading(false), 900); }; return <ScreenContainer className="px-6" edges={["top", "left", "right"]}><View style={styles.content}><CwaLogo/><View style={styles.intro}><Text style={styles.title}>مرحباً بعودتك</Text><Text style={styles.subtitle}>سجّل الدخول إلى محفظة CwaAX</Text></View><Text style={styles.label}>البريد الإلكتروني أو اسم المستخدم</Text><View style={styles.inputRow}><MaterialIcons name="person-outline" size={19} color={CWAAX.muted}/><TextInput value={email} onChangeText={setEmail} placeholder="name@email.com" placeholderTextColor="#9CA8A1" keyboardType="email-address" autoCapitalize="none" style={styles.input}/></View><Text style={styles.label}>كلمة المرور</Text><View style={styles.inputRow}><MaterialIcons name="lock-outline" size={19} color={CWAAX.muted}/><TextInput value={password} onChangeText={setPassword} placeholder="أدخل كلمة المرور" placeholderTextColor="#9CA8A1" secureTextEntry={!show} style={styles.input}/><Pressable onPress={() => setShow(!show)}><MaterialIcons name={show ? "visibility" : "visibility-off"} size={19} color={CWAAX.muted}/></Pressable></View><View style={styles.options}><Pressable onPress={() => setRemember(!remember)} style={styles.remember}><MaterialIcons name={remember ? "check-box" : "check-box-outline-blank"} size={18} color={remember ? CWAAX.green : CWAAX.muted}/><Text style={styles.optionText}>تذكر تسجيل الدخول</Text></Pressable><Pressable onPress={() => router.push("/forgot-password")}><Text style={styles.forgot}>نسيت كلمة المرور؟</Text></Pressable></View><Pressable onPress={login} disabled={loading} style={({ pressed }) => [styles.button, pressed && styles.pressed]}>{loading ? <ActivityIndicator color={CWAAX.white}/> : <><Text style={styles.buttonText}>تسجيل الدخول</Text><MaterialIcons name="arrow-back" size={18} color={CWAAX.white}/></>}</Pressable><View style={styles.divider}><View style={styles.line}/><Text style={styles.or}>أو</Text><View style={styles.line}/></View><Pressable onPress={() => Alert.alert("تسجيل سريع", "سيتم فتح تسجيل الدخول الآمن من Manus.")} style={({ pressed }) => [styles.oauth, pressed && styles.pressed]}><MaterialIcons name="account-circle" size={21} color={CWAAX.ink}/><Text style={styles.oauthText}>المتابعة بحساب Manus</Text></Pressable><View style={styles.signup}><Text style={styles.signupText}>ليس لديك حساب؟</Text><Pressable onPress={() => router.push("/register")}><Text style={styles.signupLink}> إنشاء حساب</Text></Pressable></View></View></ScreenContainer> }
const styles = StyleSheet.create({ content: { flex: 1, paddingTop: 26 }, intro: { marginTop: 55, marginBottom: 28 }, title: { color: CWAAX.ink, fontSize: 29, fontWeight: "900", textAlign: "right" }, subtitle: { color: CWAAX.muted, fontSize: 13, marginTop: 7, textAlign: "right" }, label: { color: CWAAX.ink, fontSize: 12, fontWeight: "800", textAlign: "right", marginBottom: 8, marginTop: 10 }, inputRow: { height: 52, borderWidth: 1, borderColor: CWAAX.line, borderRadius: 14, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 8 }, input: { flex: 1, color: CWAAX.ink, textAlign: "right", fontSize: 12 }, options: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 14 }, remember: { flexDirection: "row", alignItems: "center", gap: 5 }, optionText: { color: CWAAX.muted, fontSize: 10 }, forgot: { color: CWAAX.green, fontSize: 10, fontWeight: "800" }, button: { height: 52, borderRadius: 15, backgroundColor: CWAAX.green, justifyContent: "center", alignItems: "center", flexDirection: "row", gap: 8, marginTop: 24 }, buttonText: { color: CWAAX.white, fontSize: 14, fontWeight: "900" }, divider: { flexDirection: "row", alignItems: "center", gap: 10, marginVertical: 22 }, line: { flex: 1, height: 1, backgroundColor: CWAAX.line }, or: { color: CWAAX.muted, fontSize: 11 }, oauth: { height: 50, borderWidth: 1, borderColor: CWAAX.line, borderRadius: 14, justifyContent: "center", alignItems: "center", flexDirection: "row", gap: 8 }, oauthText: { color: CWAAX.ink, fontSize: 12, fontWeight: "800" }, signup: { flexDirection: "row-reverse", justifyContent: "center", marginTop: 24 }, signupText: { color: CWAAX.muted, fontSize: 11 }, signupLink: { color: CWAAX.green, fontSize: 11, fontWeight: "900" }, pressed: { opacity: .62 } });
