import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconButton } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
const items = [{ icon: "trending-up" as const, title: "تحرك قوي في XRP", text: "ارتفع XRP بنسبة 4.12% خلال 24 ساعة", time: "منذ 12 دقيقة", color: CWAAX.green }, { icon: "verified-user" as const, title: "حافظ على أمان حسابك", text: "فعّل المصادقة الثنائية لحماية أصولك", time: "منذ ساعتين", color: CWAAX.gold }, { icon: "check-circle" as const, title: "اكتملت عملية الاستقبال", text: "تمت إضافة 250 USDT إلى محفظتك", time: "أمس", color: CWAAX.green }];
export default function NotificationsScreen() { const router = useRouter(); return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><IconButton icon="arrow-forward" label="رجوع" onPress={() => router.back()}/><Text style={styles.title}>الإشعارات</Text><Pressable onPress={() => {}}><Text style={styles.markAll}>تحديد الكل</Text></Pressable></View><View style={styles.unread}><View style={styles.unreadDot}/><Text style={styles.unreadText}>لديك 2 إشعارات جديدة</Text></View>{items.map((item) => <Pressable key={item.title} onPress={() => router.push("/settings")} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: item.color === CWAAX.gold ? "#FFF5DE" : CWAAX.greenSoft }]}><MaterialIcons name={item.icon} size={20} color={item.color}/></View><View style={styles.copy}><Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.rowText}>{item.text}</Text><Text style={styles.time}>{item.time}</Text></View><View style={styles.chevron}><MaterialIcons name="chevron-left" size={18} color="#A0AAA4"/></View></Pressable>)}</ScrollView></ScreenContainer> }
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 28 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 23 }, title: { color: CWAAX.ink, fontSize: 20, fontWeight: "900" }, markAll: { color: CWAAX.green, fontSize: 11, fontWeight: "800" }, unread: { flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 6, marginBottom: 11 }, unreadDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: CWAAX.green }, unreadText: { color: CWAAX.muted, fontSize: 11 }, row: { flexDirection: "row", alignItems: "flex-start", gap: 11, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: CWAAX.line }, icon: { width: 43, height: 43, borderRadius: 15, alignItems: "center", justifyContent: "center" }, copy: { flex: 1 }, rowTitle: { color: CWAAX.ink, textAlign: "right", fontSize: 13, fontWeight: "900" }, rowText: { color: CWAAX.muted, textAlign: "right", fontSize: 11, lineHeight: 17, marginTop: 4 }, time: { color: "#A1AAA5", textAlign: "right", fontSize: 9, marginTop: 6 }, chevron: { paddingTop: 12 }, pressed: { opacity: .6 } });
