import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, IconButton, StatusPill } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
import { useAuth } from "@/hooks/use-auth";
export default function ProfileScreen() { const router = useRouter(); const { logout } = useAuth({ autoFetch: false }); const rows = [{ icon: "verified-user" as const, label: "المصادقة الثنائية", value: "غير مفعّلة", route: "/settings" }, { icon: "lock-outline" as const, label: "تغيير كلمة المرور", value: "آخر تغيير منذ 30 يوماً", route: "/settings" }, { icon: "history" as const, label: "سجل العمليات", value: "عرض كل العمليات", route: "/transactions" }]; return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><IconButton icon="arrow-forward" label="رجوع" onPress={() => router.back()}/><Text style={styles.title}>الملف الشخصي</Text><View style={{ width: 42 }}/></View><View style={styles.hero}><View style={styles.avatar}><Text style={styles.avatarText}>أ</Text></View><Text style={styles.name}>أحمد خالد</Text><Text style={styles.email}>ahmed.khaled@email.com</Text><Text style={styles.uid}>UID 928 401 76</Text><StatusPill>حساب موثّق</StatusPill></View><Text style={styles.section}>بيانات الحساب</Text><Card>{rows.map((row) => <Pressable key={row.label} onPress={() => router.push(row.route as never)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.rowIcon}><MaterialIcons name={row.icon} size={18} color={CWAAX.green}/></View><View style={styles.rowCopy}><Text style={styles.rowLabel}>{row.label}</Text><Text style={styles.rowValue}>{row.value}</Text></View><MaterialIcons name="chevron-left" size={19} color="#A0AAA4"/></Pressable>)}</Card><Text style={styles.section}>صلاحيات الحساب</Text><View style={styles.permission}><MaterialIcons name="shield" size={20} color={CWAAX.green}/><View style={{ flex: 1 }}><Text style={styles.permissionTitle}>مستخدم CwaAX</Text><Text style={styles.permissionSub}>تتم حماية الصلاحيات الحساسة من الخادم</Text></View><StatusPill tone="success">user</StatusPill></View><Pressable onPress={() => Alert.alert("تسجيل الخروج", "هل تريد تسجيل الخروج من CwaAX؟", [{ text: "إلغاء", style: "cancel" }, { text: "تسجيل الخروج", style: "destructive", onPress: async () => { await logout(); router.replace("/login"); } }])} style={({ pressed }) => [styles.logout, pressed && styles.pressed]}><MaterialIcons name="logout" size={18} color={CWAAX.red}/><Text style={styles.logoutText}>تسجيل الخروج</Text></Pressable></ScrollView></ScreenContainer> }
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 30 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }, title: { color: CWAAX.ink, fontSize: 20, fontWeight: "900" }, hero: { alignItems: "center", paddingBottom: 24, borderBottomWidth: 1, borderBottomColor: CWAAX.line }, avatar: { width: 76, height: 76, borderRadius: 28, backgroundColor: CWAAX.green, alignItems: "center", justifyContent: "center", marginBottom: 11 }, avatarText: { color: CWAAX.white, fontSize: 32, fontWeight: "900" }, name: { color: CWAAX.ink, fontSize: 19, fontWeight: "900" }, email: { color: CWAAX.muted, fontSize: 11, marginTop: 5 }, uid: { color: CWAAX.muted, fontSize: 10, marginTop: 5, marginBottom: 10 }, section: { color: CWAAX.muted, fontSize: 12, fontWeight: "800", textAlign: "right", marginTop: 23, marginBottom: 9 }, row: { minHeight: 65, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: CWAAX.line }, rowIcon: { width: 35, height: 35, borderRadius: 12, backgroundColor: CWAAX.greenSoft, alignItems: "center", justifyContent: "center" }, rowCopy: { flex: 1 }, rowLabel: { color: CWAAX.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, rowValue: { color: CWAAX.muted, fontSize: 10, marginTop: 4, textAlign: "right" }, permission: { borderWidth: 1, borderColor: CWAAX.line, borderRadius: 16, padding: 14, flexDirection: "row", alignItems: "center", gap: 10 }, permissionTitle: { color: CWAAX.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, permissionSub: { color: CWAAX.muted, fontSize: 10, marginTop: 4, textAlign: "right" }, logout: { marginTop: 23, borderWidth: 1, borderColor: "#F2D1CF", backgroundColor: "#FFF8F8", borderRadius: 14, height: 48, justifyContent: "center", alignItems: "center", flexDirection: "row", gap: 7 }, logoutText: { color: CWAAX.red, fontSize: 12, fontWeight: "800" }, pressed: { opacity: .62 } });
