import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { CwaLogo } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
export default function RegisterScreen() { const router = useRouter(); const [agree, setAgree] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const submit = () => { if (!name || !email || !agree) { Alert.alert("أكمل البيانات", "أدخل الاسم والبريد ووافق على الشروط."); return; } Alert.alert("تم إنشاء الحساب", "تحقق من بريدك الإلكتروني لإكمال التسجيل.", [{ text: "متابعة", onPress: () => router.replace("/login") }]); }; return <ScreenContainer className="px-6" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><CwaLogo/><View style={styles.intro}><Text style={styles.title}>أنشئ حسابك</Text><Text style={styles.subtitle}>ابدأ رحلتك مع CwaAX اليوم</Text></View><Text style={styles.label}>الاسم الكامل</Text><View style={styles.input}><MaterialIcons name="person-outline" size={18} color={CWAAX.muted}/><TextInput value={name} onChangeText={setName} placeholder="أحمد خالد" placeholderTextColor="#9CA8A1" style={styles.field}/></View><Text style={styles.label}>البريد الإلكتروني</Text><View style={styles.input}><MaterialIcons name="mail-outline" size={18} color={CWAAX.muted}/><TextInput value={email} onChangeText={setEmail} placeholder="name@email.com" placeholderTextColor="#9CA8A1" style={styles.field} keyboardType="email-address"/></View><Text style={styles.label}>كلمة المرور</Text><View style={styles.input}><MaterialIcons name="lock-outline" size={18} color={CWAAX.muted}/><TextInput placeholder="8 أحرف على الأقل" placeholderTextColor="#9CA8A1" style={styles.field} secureTextEntry/></View><Pressable onPress={() => setAgree(!agree)} style={styles.agree}><MaterialIcons name={agree ? "check-box" : "check-box-outline-blank"} size={18} color={agree ? CWAAX.green : CWAAX.muted}/><Text style={styles.agreeText}>أوافق على <Text style={styles.link}>شروط الاستخدام وسياسة الخصوصية</Text></Text></Pressable><Pressable onPress={submit} style={({ pressed }) => [styles.button, pressed && styles.pressed]}><Text style={styles.buttonText}>إنشاء الحساب</Text><MaterialIcons name="arrow-back" size={18} color={CWAAX.white}/></Pressable><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>لديك حساب بالفعل؟ تسجيل الدخول</Text></Pressable></ScrollView></ScreenContainer> }
const styles = StyleSheet.create({ content: { paddingTop: 26, paddingBottom: 30 }, intro: { marginTop: 50, marginBottom: 22 }, title: { color: CWAAX.ink, textAlign: "right", fontSize: 28, fontWeight: "900" }, subtitle: { color: CWAAX.muted, textAlign: "right", fontSize: 12, marginTop: 6 }, label: { color: CWAAX.ink, textAlign: "right", fontSize: 12, fontWeight: "800", marginBottom: 8, marginTop: 10 }, input: { height: 52, borderWidth: 1, borderColor: CWAAX.line, borderRadius: 14, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 13 }, field: { flex: 1, color: CWAAX.ink, textAlign: "right", fontSize: 12 }, agree: { flexDirection: "row-reverse", alignItems: "center", gap: 6, marginTop: 17 }, agreeText: { color: CWAAX.muted, fontSize: 10 }, link: { color: CWAAX.green, fontWeight: "800" }, button: { height: 52, borderRadius: 15, backgroundColor: CWAAX.green, justifyContent: "center", alignItems: "center", flexDirection: "row", gap: 8, marginTop: 24 }, buttonText: { color: CWAAX.white, fontSize: 14, fontWeight: "900" }, back: { alignItems: "center", marginTop: 22 }, backText: { color: CWAAX.green, fontSize: 11, fontWeight: "800" }, pressed: { opacity: .62 } });
