import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { CwaLogo } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
import { trpc } from "@/lib/trpc";
import * as Auth from "@/lib/_core/auth";
export default function RegisterScreen() { const router=useRouter(); const [agree,setAgree]=useState(false); const [name,setName]=useState(""); const [username,setUsername]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [loading,setLoading]=useState(false); const register=trpc.auth.register.useMutation(); const submit=async()=>{ if(!name.trim()||!username.trim()||!email.trim()||!password||!confirm||!agree)return Alert.alert("أكمل البيانات","أدخل جميع البيانات ووافق على الشروط."); if(password!==confirm)return Alert.alert("كلمة المرور","كلمتا المرور غير متطابقتين."); setLoading(true); try{const result=await register.mutateAsync({name:name.trim(),username:username.trim(),email:email.trim(),password}); if(result.token)await Auth.setSessionToken(result.token); await Auth.setUserInfo({...result.user,lastSignedIn:new Date(result.user.lastSignedIn)}); router.replace("/(tabs)");}catch(e:any){Alert.alert("تعذر إنشاء الحساب",e?.message||"حاول مرة أخرى.");}finally{setLoading(false)}}; return <ScreenContainer className="px-6" edges={["top","left","right"]}><ScrollView contentContainerStyle={styles.content}><CwaLogo/><View style={styles.intro}><Text style={styles.title}>أنشئ حسابك</Text><Text style={styles.subtitle}>حساب CwaAX مرتبط بقاعدة البيانات ويمكن استخدامه من أي جهاز.</Text></View><Field label="الاسم الكامل" value={name} onChangeText={setName} icon="person-outline" placeholder="أحمد خالد"/><Field label="اسم المستخدم" value={username} onChangeText={setUsername} icon="alternate-email" placeholder="ahmed_123" autoCapitalize="none"/><Field label="البريد الإلكتروني" value={email} onChangeText={setEmail} icon="mail-outline" placeholder="name@email.com" autoCapitalize="none" keyboardType="email-address"/><Field label="كلمة المرور" value={password} onChangeText={setPassword} icon="lock-outline" placeholder="8 أحرف على الأقل" secureTextEntry/><Field label="تأكيد كلمة المرور" value={confirm} onChangeText={setConfirm} icon="lock-outline" placeholder="أعد كتابة كلمة المرور" secureTextEntry/><Pressable onPress={()=>setAgree(!agree)} style={styles.agree}><MaterialIcons name={agree?"check-box":"check-box-outline-blank"} size={18} color={agree?CWAAX.green:CWAAX.muted}/><Text style={styles.agreeText}>أوافق على شروط الاستخدام وسياسة الخصوصية</Text></Pressable><Pressable onPress={submit} disabled={loading} style={({pressed})=>[styles.button,pressed&&styles.pressed]}>{loading?<ActivityIndicator color={CWAAX.white}/>:<><Text style={styles.buttonText}>إنشاء الحساب</Text><MaterialIcons name="arrow-back" size={18} color={CWAAX.white}/></>}</Pressable><Pressable onPress={()=>router.replace("/login")} style={styles.back}><Text style={styles.backText}>لديك حساب بالفعل؟ تسجيل الدخول</Text></Pressable></ScrollView></ScreenContainer> }
function Field(p:any){return <><Text style={styles.label}>{p.label}</Text><View style={styles.input}><MaterialIcons name={p.icon} size={18} color={CWAAX.muted}/><TextInput {...p} style={styles.field}/></View></>}
const styles=StyleSheet.create({content:{paddingTop:26,paddingBottom:30},intro:{marginTop:42,marginBottom:16},title:{color:CWAAX.ink,textAlign:"right",fontSize:28,fontWeight:"900"},subtitle:{color:CWAAX.muted,textAlign:"right",fontSize:11,marginTop:6},label:{color:CWAAX.ink,textAlign:"right",fontSize:12,fontWeight:"800",marginBottom:8,marginTop:10},input:{height:52,borderWidth:1,borderColor:CWAAX.line,borderRadius:14,flexDirection:"row",alignItems:"center",gap:8,paddingHorizontal:13},field:{flex:1,color:CWAAX.ink,textAlign:"right",fontSize:12},agree:{flexDirection:"row-reverse",alignItems:"center",gap:6,marginTop:17},agreeText:{color:CWAAX.muted,fontSize:10},button:{height:52,borderRadius:15,backgroundColor:CWAAX.green,justifyContent:"center",alignItems:"center",flexDirection:"row",gap:8,marginTop:24},buttonText:{color:CWAAX.white,fontSize:14,fontWeight:"900"},back:{alignItems:"center",marginTop:22},backText:{color:CWAAX.green,fontSize:11,fontWeight:"800"},pressed:{opacity:.62}});
