import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, IconButton } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
const items = [{ label: "المصادقة الثنائية", icon: "verified-user" as const, sub: "حماية إضافية لحسابك" }, { label: "الإشعارات", icon: "notifications-none" as const, sub: "تنبيهات الأسعار والعمليات" }, { label: "العملة الأصلية", icon: "paid" as const, sub: "USD · الدولار الأمريكي" }, { label: "اللغة", icon: "language" as const, sub: "العربية" }];
export default function SettingsScreen() { const router = useRouter(); const [twoFactor, setTwoFactor] = useState(false); return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><IconButton icon="arrow-forward" label="رجوع" onPress={() => router.back()}/><Text style={styles.title}>الإعدادات</Text><View style={{ width: 42 }}/></View><Card style={styles.banner}><MaterialIcons name="security" size={23} color={CWAAX.green}/><View style={styles.bannerCopy}><Text style={styles.bannerTitle}>اجعل حسابك أكثر أماناً</Text><Text style={styles.bannerSub}>فعّل المصادقة الثنائية الآن</Text></View><Pressable onPress={() => setTwoFactor(!twoFactor)} style={({ pressed }) => [styles.enable, pressed && styles.pressed]}><Text style={styles.enableText}>{twoFactor ? "مفعّلة" : "تفعيل"}</Text></Pressable></Card><Text style={styles.section}>الأمان والخصوصية</Text><Card>{items.map((item) => <View key={item.label} style={styles.row}><View style={styles.icon}><MaterialIcons name={item.icon} size={18} color={CWAAX.green}/></View><View style={styles.copy}><Text style={styles.label}>{item.label}</Text><Text style={styles.sub}>{item.sub}</Text></View>{item.label === "المصادقة الثنائية" ? <Switch value={twoFactor} onValueChange={setTwoFactor} trackColor={{ false: "#DDE4E0", true: "#9BD5B4" }} thumbColor={twoFactor ? CWAAX.green : "#fff"}/> : <MaterialIcons name="chevron-left" size={19} color="#A0AAA4"/>}</View>)}</Card><Text style={styles.section}>الدعم</Text><Card><Pressable onPress={() => router.push("/support")} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: "#FFF5DE" }]}><MaterialIcons name="support-agent" size={18} color={CWAAX.gold}/></View><View style={styles.copy}><Text style={styles.label}>مركز الدعم</Text><Text style={styles.sub}>نحن هنا لمساعدتك</Text></View><MaterialIcons name="chevron-left" size={19} color="#A0AAA4"/></Pressable><Pressable onPress={() => Alert.alert("الشروط والسياسات", "سيتم عرض شروط الاستخدام وسياسة الخصوصية هنا.")} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: "#F2F3F2" }]}><MaterialIcons name="description" size={18} color={CWAAX.ink}/></View><View style={styles.copy}><Text style={styles.label}>الشروط والسياسات</Text><Text style={styles.sub}>آخر تحديث: سبتمبر 2026</Text></View><MaterialIcons name="chevron-left" size={19} color="#A0AAA4"/></Pressable></Card><Text style={styles.version}>CwaAX Wallet · الإصدار 1.0.0</Text></ScrollView></ScreenContainer> }
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 30 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 23 }, title: { color: CWAAX.ink, fontSize: 20, fontWeight: "900" }, banner: { flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: "#F0F9F4", borderColor: "#D8F0E1", marginBottom: 22 }, bannerCopy: { flex: 1 }, bannerTitle: { color: CWAAX.ink, fontSize: 12, fontWeight: "900", textAlign: "right" }, bannerSub: { color: CWAAX.muted, fontSize: 10, marginTop: 4, textAlign: "right" }, enable: { backgroundColor: CWAAX.green, borderRadius: 9, paddingHorizontal: 9, paddingVertical: 7 }, enableText: { color: CWAAX.white, fontSize: 10, fontWeight: "800" }, section: { color: CWAAX.muted, fontWeight: "800", fontSize: 12, textAlign: "right", marginBottom: 9, marginTop: 5 }, row: { minHeight: 65, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: CWAAX.line }, icon: { width: 35, height: 35, borderRadius: 12, backgroundColor: CWAAX.greenSoft, alignItems: "center", justifyContent: "center" }, copy: { flex: 1 }, label: { color: CWAAX.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, sub: { color: CWAAX.muted, fontSize: 10, marginTop: 4, textAlign: "right" }, version: { color: "#A3AEA7", textAlign: "center", fontSize: 10, marginTop: 23 }, pressed: { opacity: .62 } });
