import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, IconButton } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
export default function SupportScreen() { const router = useRouter(); const [message, setMessage] = useState(""); return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View style={styles.header}><IconButton icon="arrow-forward" label="رجوع" onPress={() => router.back()}/><Text style={styles.title}>دعم CwaAX</Text><IconButton icon="more-horiz" label="المزيد"/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.agent}><View style={styles.agentAvatar}><MaterialIcons name="support-agent" size={22} color={CWAAX.green}/></View><View><Text style={styles.agentName}>فريق دعم CwaAX</Text><Text style={styles.online}>متصل الآن</Text></View></View><View style={styles.date}><Text style={styles.dateText}>اليوم</Text></View><View style={styles.bubble}><Text style={styles.bubbleText}>مرحباً أحمد، أهلاً بك في CwaAX. كيف يمكننا مساعدتك اليوم؟</Text><Text style={styles.bubbleTime}>10:42 ص</Text></View><View style={styles.quick}><Text style={styles.quickTitle}>أسئلة شائعة</Text>{["كيف أضيف رصيداً؟", "أين أجد سجل العمليات؟", "كيف أفعّل المصادقة الثنائية؟"].map((q) => <Pressable key={q} onPress={() => setMessage(q)} style={({ pressed }) => [styles.question, pressed && styles.pressed]}><Text style={styles.questionText}>{q}</Text><MaterialIcons name="arrow-outward" size={14} color={CWAAX.green}/></Pressable>)}</View></ScrollView><View style={styles.composer}><TextInput value={message} onChangeText={setMessage} placeholder="اكتب رسالتك..." placeholderTextColor="#9CA8A1" style={styles.input} textAlign="right"/><Pressable onPress={() => { if (!message) { Alert.alert("اكتب رسالة", "أدخل رسالتك أولاً."); return; } Alert.alert("تم الإرسال", "سيرد عليك فريق الدعم قريباً."); setMessage(""); }} style={({ pressed }) => [styles.send, pressed && styles.pressed]}><MaterialIcons name="send" size={18} color={CWAAX.white}/></Pressable></View></ScreenContainer> }
const styles = StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 25 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 12 }, title: { color: CWAAX.ink, fontSize: 19, fontWeight: "900" }, agent: { flexDirection: "row-reverse", alignItems: "center", gap: 10, paddingBottom: 17, borderBottomWidth: 1, borderBottomColor: CWAAX.line }, agentAvatar: { width: 42, height: 42, borderRadius: 14, backgroundColor: CWAAX.greenSoft, alignItems: "center", justifyContent: "center" }, agentName: { color: CWAAX.ink, fontSize: 13, fontWeight: "900", textAlign: "right" }, online: { color: CWAAX.green, fontSize: 10, marginTop: 3, textAlign: "right" }, date: { alignItems: "center", marginVertical: 18 }, dateText: { color: CWAAX.muted, backgroundColor: CWAAX.surface, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, fontSize: 10 }, bubble: { alignSelf: "flex-end", backgroundColor: CWAAX.green, maxWidth: "86%", borderRadius: 17, borderTopRightRadius: 4, padding: 12 }, bubbleText: { color: CWAAX.white, fontSize: 12, lineHeight: 19, textAlign: "right" }, bubbleTime: { color: "#BDE8CE", fontSize: 9, textAlign: "left", marginTop: 5 }, quick: { marginTop: 29 }, quickTitle: { color: CWAAX.muted, fontSize: 11, textAlign: "right", fontWeight: "800", marginBottom: 10 }, question: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", borderWidth: 1, borderColor: CWAAX.line, borderRadius: 12, padding: 12, marginBottom: 8 }, questionText: { color: CWAAX.ink, fontSize: 11, fontWeight: "700" }, composer: { borderTopWidth: 1, borderTopColor: CWAAX.line, paddingTop: 10, paddingBottom: 10, flexDirection: "row", gap: 8 }, input: { flex: 1, height: 44, borderWidth: 1, borderColor: CWAAX.line, borderRadius: 14, paddingHorizontal: 13, color: CWAAX.ink, fontSize: 12 }, send: { width: 44, height: 44, borderRadius: 14, backgroundColor: CWAAX.green, alignItems: "center", justifyContent: "center" }, pressed: { opacity: .62 } });
