import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconButton, StatusPill } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
import { trpc } from "@/lib/trpc";
export default function TransactionsScreen() { const router = useRouter(); const txs = trpc.wallet.transactions.useQuery(); return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View style={styles.header}><IconButton icon="arrow-forward" label="رجوع" onPress={() => router.back()}/><Text style={styles.title}>سجل العمليات</Text><IconButton icon="tune" label="فلترة"/></View><View style={styles.summary}><Text style={styles.summaryLabel}>إجمالي العمليات</Text><Text style={styles.summaryValue}>{txs.data?.length ?? 0} عملية</Text><Text style={styles.summarySub}>{txs.isLoading ? "جاري التحديث..." : "متصل بقاعدة البيانات"}</Text></View><View style={styles.filters}><Text style={styles.filterActive}>الكل</Text><Text style={styles.filter}>إيداع</Text><Text style={styles.filter}>سحب</Text><Text style={styles.filter}>تبديل</Text></View><FlatList data={txs.data || []} keyExtractor={(item:any) => item.transactionId} renderItem={({ item }:any) => { const positive = item.type === "deposit"; return <Pressable style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={[styles.txIcon, { backgroundColor: positive ? CWAAX.greenSoft : "#F2F3F2" }]}><MaterialIcons name={positive ? "call-received" : "swap-horizontal-circle"} size={20} color={positive ? CWAAX.green : CWAAX.ink}/></View><View style={styles.copy}><Text style={styles.txTitle}>{item.type === "deposit" ? "إيداع" : item.type === "withdrawal" ? "سحب" : item.type}</Text><Text style={styles.meta}>{item.transactionId} · {new Date(item.createdAt).toLocaleString()}</Text></View><View style={styles.amount}><Text style={[styles.amountText, positive && styles.positive]}>{positive ? "+" : "-"} {String(item.amount)} {item.currency}</Text><StatusPill>{item.status}</StatusPill></View></Pressable> }} contentContainerStyle={{ paddingBottom: 28 }}/></ScreenContainer> }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 12, marginBottom: 23 }, title: { color: CWAAX.ink, fontSize: 20, fontWeight: "900" }, summary: { padding: 18, backgroundColor: CWAAX.ink, borderRadius: 19, marginBottom: 18 }, summaryLabel: { color: "#AABBB1", fontSize: 11, textAlign: "right" }, summaryValue: { color: CWAAX.white, fontSize: 26, fontWeight: "900", textAlign: "right", marginTop: 9 }, summarySub: { color: "#8CA096", fontSize: 10, textAlign: "right", marginTop: 4 }, filters: { flexDirection: "row-reverse", gap: 22, borderBottomWidth: 1, borderBottomColor: CWAAX.line, paddingBottom: 13, marginBottom: 4 }, filterActive: { color: CWAAX.green, fontSize: 12, fontWeight: "900" }, filter: { color: CWAAX.muted, fontSize: 12, fontWeight: "700" }, row: { flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: CWAAX.line, paddingVertical: 14 }, txIcon: { width: 41, height: 41, borderRadius: 14, justifyContent: "center", alignItems: "center" }, copy: { flex: 1 }, txTitle: { color: CWAAX.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, meta: { color: CWAAX.muted, fontSize: 9, marginTop: 5, textAlign: "right" }, amount: { alignItems: "flex-end", gap: 6 }, amountText: { color: CWAAX.ink, fontSize: 11, fontWeight: "800" }, positive: { color: CWAAX.green }, pressed: { opacity: .6 } });
