import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { CwaLogo, IconButton } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
const chats = [{ id: "1", title: "فريق دعم CwaAX", text: "مرحباً، كيف يمكننا مساعدتك؟", time: "10:42", icon: "support-agent" as const, unread: 2 }, { id: "2", title: "تنبيهات الأمان", text: "تم تسجيل الدخول من جهاز جديد", time: "أمس", icon: "shield" as const, unread: 0 }, { id: "3", title: "مجتمع المتداولين", text: "تابع آخر تحليلات السوق اليوم", time: "28 أغسطس", icon: "groups" as const, unread: 0 }];
export default function MessagesScreen() { const router = useRouter(); const [filter, setFilter] = useState("الكل"); const [query, setQuery] = useState(""); const filteredChats = useMemo(() => chats.filter((chat) => (filter === "غير مقروءة" ? chat.unread > 0 : filter === "الدعم" ? chat.title.includes("دعم") : true)).filter((chat) => `${chat.title} ${chat.text}`.toLowerCase().includes(query.toLowerCase())), [filter, query]); return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View style={styles.header}><CwaLogo/><View style={styles.actions}><IconButton icon="search" label="البحث" onPress={() => setQuery(query ? "" : "دعم")} /><IconButton icon="edit" label="رسالة جديدة" onPress={() => router.push("/support")}/></View></View><Text style={styles.title}>المحادثات</Text><Text style={styles.subtitle}>كل ما يهمك في مكان واحد</Text><View style={styles.filterRow}>{["الكل", "غير مقروءة", "الدعم"].map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[filter === item ? styles.filterActive : styles.filterButton]}><Text style={filter === item ? styles.filterActiveText : styles.filterText}>{item}</Text></Pressable>)}</View>{query ? <TextInput value={query} onChangeText={setQuery} placeholder="ابحث في المحادثات" placeholderTextColor="#9CA8A1" style={styles.searchInput} textAlign="right"/> : null}<FlatList data={filteredChats} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <Pressable onPress={() => router.push("/support")} style={({ pressed }) => [styles.chatRow, pressed && styles.pressed]}><View style={styles.avatar}><MaterialIcons name={item.icon} size={21} color={CWAAX.green}/></View><View style={styles.chatCopy}><View style={styles.chatHead}><Text style={styles.time}>{item.time}</Text><Text style={styles.chatTitle}>{item.title}</Text></View><Text style={styles.chatText}>{item.text}</Text></View>{item.unread > 0 && <View style={styles.unread}><Text style={styles.unreadText}>{item.unread}</Text></View>}</Pressable>} /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 12 }, actions: { flexDirection: "row", gap: 8 }, title: { color: CWAAX.ink, fontSize: 27, fontWeight: "900", textAlign: "right", marginTop: 24 }, subtitle: { color: CWAAX.muted, textAlign: "right", fontSize: 12, marginTop: 5 }, filterRow: { flexDirection: "row-reverse", alignItems: "center", gap: 22, borderBottomWidth: 1, borderBottomColor: CWAAX.line, paddingVertical: 20, marginBottom: 4 }, filterActive: { backgroundColor: CWAAX.greenSoft, borderRadius: 9, paddingHorizontal: 12, paddingVertical: 7 }, filterActiveText: { color: CWAAX.green, fontSize: 12, fontWeight: "800" }, filterButton: { paddingHorizontal: 2, paddingVertical: 7 }, filterText: { color: CWAAX.muted, fontSize: 12, fontWeight: "700" }, searchInput: { height: 44, borderWidth: 1, borderColor: CWAAX.line, borderRadius: 13, paddingHorizontal: 12, color: CWAAX.ink, marginBottom: 8 }, list: { paddingBottom: 25 }, chatRow: { minHeight: 80, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: CWAAX.line, paddingVertical: 14 }, avatar: { width: 47, height: 47, borderRadius: 17, backgroundColor: CWAAX.greenSoft, alignItems: "center", justifyContent: "center" }, chatCopy: { flex: 1 }, chatHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, chatTitle: { color: CWAAX.ink, fontSize: 13, fontWeight: "800", textAlign: "right" }, time: { color: CWAAX.muted, fontSize: 10 }, chatText: { color: CWAAX.muted, fontSize: 11, textAlign: "right", marginTop: 7 }, unread: { backgroundColor: CWAAX.green, width: 21, height: 21, borderRadius: 8, alignItems: "center", justifyContent: "center" }, unreadText: { color: CWAAX.white, fontSize: 11, fontWeight: "900" }, pressed: { opacity: 0.6 } });
