import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, CwaLogo, IconButton, StatusPill } from "@/components/cwaax-ui";
import { CWAAX } from "@/constants/cwaax";
export default function PredictScreen() { const router = useRouter(); const [selected, setSelected] = useState("BTC"); const assets = [{ symbol: "BTC", name: "Bitcoin", price: "$67,240", outlook: "إيجابي", color: "#D98931", score: "82" }, { symbol: "ETH", name: "Ethereum", price: "$3,487", outlook: "مستقر", color: "#6675D1", score: "68" }, { symbol: "XRP", name: "XRP", price: "$0.4671", outlook: "إيجابي", color: "#232B32", score: "76" }]; return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.header}><CwaLogo/><IconButton icon="notifications-none" label="الإشعارات" onPress={() => router.push("/notifications")}/></View><Text style={styles.kicker}>تحليلات مبسطة</Text><Text style={styles.title}>توقع السوق</Text><Text style={styles.subtitle}>إشارات تساعدك على اتخاذ قرار أكثر وضوحاً</Text><Card style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="auto-awesome" size={22} color={CWAAX.green}/></View><View style={styles.heroCopy}><Text style={styles.heroTitle}>مؤشر السوق العام</Text><Text style={styles.heroSub}>الاتجاه الحالي يميل للصعود</Text></View><Text style={styles.heroScore}>+6.4%</Text></Card><Text style={styles.sectionLabel}>الأصول المتابعة</Text>{assets.map((asset) => <Pressable key={asset.symbol} onPress={() => setSelected(asset.symbol)} style={({ pressed }) => [styles.assetRow, selected === asset.symbol && styles.assetSelected, pressed && styles.pressed]}><View style={[styles.assetDot, { backgroundColor: asset.color }]}><Text style={styles.assetLetter}>{asset.symbol[0]}</Text></View><View style={styles.assetName}><Text style={styles.assetSymbol}>{asset.symbol}/USDT</Text><Text style={styles.assetPrice}>{asset.price}</Text></View><View style={styles.signal}><StatusPill>{asset.outlook}</StatusPill><Text style={styles.signalScore}>ثقة {asset.score}%</Text></View><MaterialIcons name="chevron-left" size={18} color={CWAAX.muted}/></Pressable>)}<Card style={styles.note}><MaterialIcons name="lightbulb-outline" size={20} color={CWAAX.gold}/><View style={styles.noteCopy}><Text style={styles.noteTitle}>تنبيه ذكي</Text><Text style={styles.noteText}>التوقعات ليست نصيحة مالية. راقب إدارة المخاطر قبل أي صفقة.</Text></View></Card></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 30 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 25 }, kicker: { color: CWAAX.muted, textAlign: "right", fontSize: 12 }, title: { color: CWAAX.ink, textAlign: "right", fontSize: 28, fontWeight: "900", marginTop: 4 }, subtitle: { color: CWAAX.muted, textAlign: "right", fontSize: 12, marginTop: 6, marginBottom: 18 }, hero: { flexDirection: "row", alignItems: "center", backgroundColor: "#F0F9F4", borderColor: "#D8F0E1", marginBottom: 24 }, heroIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: CWAAX.white, alignItems: "center", justifyContent: "center" }, heroCopy: { flex: 1, marginHorizontal: 11 }, heroTitle: { color: CWAAX.ink, fontSize: 13, fontWeight: "800", textAlign: "right" }, heroSub: { color: CWAAX.muted, fontSize: 10, marginTop: 4, textAlign: "right" }, heroScore: { color: CWAAX.green, fontWeight: "900", fontSize: 16 }, sectionLabel: { color: CWAAX.ink, fontWeight: "800", fontSize: 16, textAlign: "right", marginBottom: 10 }, assetRow: { flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderRadius: 16, borderWidth: 1, borderColor: CWAAX.line, marginBottom: 9 }, assetSelected: { backgroundColor: "#FAFDFC", borderColor: "#BDE4CB" }, assetDot: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, assetLetter: { color: CWAAX.white, fontWeight: "900" }, assetName: { flex: 1 }, assetSymbol: { color: CWAAX.ink, fontSize: 13, fontWeight: "800", textAlign: "right" }, assetPrice: { color: CWAAX.muted, fontSize: 10, marginTop: 3, textAlign: "right" }, signal: { alignItems: "flex-end", gap: 5 }, signalScore: { color: CWAAX.muted, fontSize: 9 }, note: { flexDirection: "row", alignItems: "flex-start", gap: 10, marginTop: 16, backgroundColor: "#FFF9EC", borderColor: "#F6E5B8" }, noteCopy: { flex: 1 }, noteTitle: { color: CWAAX.ink, fontWeight: "800", textAlign: "right", fontSize: 12 }, noteText: { color: CWAAX.muted, fontSize: 11, lineHeight: 17, textAlign: "right", marginTop: 4 }, pressed: { opacity: .6 } });
